config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :requests

  resources :toolbelts
  resources :craftsman
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :users do 
    resources :toolbelts
  end
  root to: "craftsman#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/craftsman_controller.rb
class CraftsmanController < ApplicationController
    def index
        
        if current_user
            set_user
            
            
        end
        @users = User.all
        @skills = Skill.all
        # @skill = Toolbelt.search(params[:search])
    end

    def show
        if current_user

            @user = User.find_by(id: current_user.id)
        end
        @toolbelt = Toolbelt.new
        @skills = Skill.all
    end

    private

    def set_user 
      @user = User.find_by(id: current_user.id)
    end
end

app/helpers/craftsman_helper.rb
module CraftsmanHelper
end

app/views/craftsman/_index.html.erb
<br>

<%= render partial: "navbar", locals: {user: @user}%>

<h1>welcome to craftsman repository </h1>

<p>this is a place where you can find skilled leather craftsman</p>

<h3>what kind of work are you looking for?</h3>

<% @skills.each do |skill| %>

<%= render partial: 'skills/show', locals: {skill: skill} %>

<% end %>
<h2> If none of the above craftsman listed in your area list your project type, submit a request below to have our administrators help find a craftsman.</h2>


<%= link_to "requests", new_request_path %>

app/views/craftsman/_navbar.html.erb
<% if !current_user %>

<%= link_to 'login', new_user_session_path %>
<% else %>

<%= link_to 'logout', destroy_user_session_path, method: :delete %>
<%= link_to 'home', root_path %>
<%= link_to 'my profile', craftsman_path(current_user.id) %>
<% end %>

app/views/craftsman/_request_form.html.erb
<%= form_for @user_details do |f| %>

<br>
  <div>
    <%= f.label "name" %><br />
    <%= f.text_field :name, class: 'field' %>
  </div>
  <div>
    <%= f.label "email" %><br />
    <%= f.text_field :state, class: 'field' %>
  </div>

  <div>
    <%= f.label "phone_number" %><br />
    <%= f.text_field :phone_number, class: 'field' %>
  </div>

  <div>
    <%= f.label "description" %><br />
    <%= f.text_field :description, class: 'field' %>
  </div>
  <%= flash[:errors] if flash[:errors] %>
  <%= f.submit %>
  <% end %>

app/views/craftsman/index.html.erb
<br>

<%= render partial: "navbar", locals: {user: @user}%>

<h1>welcome to craftsman repository </h1>

<p>this is a place where you can find skilled leather craftsman</p>

<h3>what kind of work are you looking for?</h3>

<% @skills.each do |skill| %>

<%= render partial: 'skills/show', locals: {skill: skill} %>

<% end %>
<h2> If none of the above craftsman listed in your area list your project type, submit a request below to have our administrators help find a craftsman.</h2>


<%= link_to "requests", new_request_path %>

app/views/craftsman/show.html.erb
<br>
<%= render partial: 'navbar' %>
<br>
<%= @user.name %>
<br>
<%= @user.email %>
<br>
<%= @user.phone_number %>
<br>
<%= @user.city %>
<br>
<%= @user.state %>

<%= link_to 'update my information', edit_user_registration_path %>

<br>
<%# <%=link_to 'my skills', user_toolbelts_path(@user.id) %> 

<%= render  'toolbelts/index'  %>


<%= render partial: 'toolbelts/new', locals: {skills: @skills, toolbelt: @toolbelt} %>