config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :requests

  resources :toolbelts
  resources :craftsman
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :users do 
    resources :toolbelts
  end
  root to: "craftsman#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/toolbelt.rb
class Toolbelt < ApplicationRecord
        belongs_to :user 
        belongs_to :skill


end

app/controllers/toolbelts_controller.rb
class ToolbeltsController < ApplicationController
        before_action :set_toolbelt, only: [:edit, :update, :destroy] 


        
        def index 
           if  current_user
               @toolbelts = current_user.toolbelts
           else 
               @toolbelts = Toolbelt.all
           end
           @skills = Skill.all
           @toolbelt = Toolbelt.new
        end
   
   
       def new 
            @skills = Skill.all
           @toolbelt = Toolbelt.new
        #    @toolbelt.build_person_of_interest
       end
       def create 
        #    @toolbelt = current_user.toolbelts.build(toolbelt_params)
        @toolbelt = Toolbelt.new(toolbelt_params)

           if @toolbelt.save 
               redirect_to craftsman_path(current_user.id)
           else 
               flash.now[:errors] = @toolbelt.errors.full_messages
               render :new 
   
           end
       end
       def edit
       end
       
       def update
   
       if @toolbelt.update(toolbelt_params)
           redirect_to root 
       else
           flash.now[:errors] = "please make sure each field is filled out correctly"
               render :new
           render :edit
       end
       end
   
       def destroy
        byebug
       @toolbelt.destroy
       flash[:notice] = "skill removed."
       redirect_to craftsman_path(current_user.id)
       end

   
       private
       def set_toolbelt
           @toolbelt = Toolbelt.find(params[:id])
       end
       def toolbelt_params
       params.require(:toolbelt).permit(:user_id, :skill_id )
       end


end

app/helpers/toolbelt_helper.rb
module ToolbeltHelper
end

app/views/toolbelts/_form.html.erb
<%= form_for @toolbelt do |f| %>
<div>
    <%= f.label "skill" %><br />
    <%= f.select :skill_id, skills.map {|skill| [skill.title, skill.id]} %>

  </div>
  <%= f.hidden_field(:user_id, value: current_user.id) %>
  <%= f.submit "Add Skill"%>
  <% end %>

app/views/toolbelts/_index.html.erb
<br>

<% if !current_user.skills.empty?%>

<% current_user.toolbelts.each do |toolbelt| %>
<br>
    <%= render partial: 'toolbelts/show', locals: {toolbelt: toolbelt} %>

    
<% end %>
<% else %>
you dont have any skills in your toolbelt yet
<% end %>
<br>
<%# <%= link_to "add a skill", new_toolbelt_path %>

app/views/toolbelts/_new.html.erb
<%# <%= byebug %> 
<%= form_for toolbelt do |f| %>
<div>
    <%= f.label "skill" %><br />
    <%= f.select :skill_id, skills.map {|skill| [skill.title, skill.id]} %>

  </div>
  <%= f.hidden_field(:user_id, value: current_user.id) %>
  <%= f.submit "Add Skill"%>
  <% end %>

app/views/toolbelts/_show.html.erb
<%= toolbelt.skill.title %>

<%= button_to "delete", toolbelt_path(toolbelt), :method => "delete", :class => 'destroy' %>

app/views/toolbelts/index.html.erb
<%= render partial: "crafsman/navbar"%>
<br>

<% if !current_user.skills.empty?%>

<% current_user.skills.each do |skill| %>
<br>
    <%= skill.title %>
<% end %>
<% else %>
you dont have any skills in your toolbelt yet
<% end %>
<br>
<%# <%= link_to "add a skill", new_toolbelt_path %>

<%= render partial: 'new', locals: {skills: @skills, toolbelt: @toolbelt} %>

app/views/toolbelts/new.html.erb
<%= render partial: 'form' %>